//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNU.Getopt.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNU.Getopt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: option &apos;&apos;{1}&apos;&apos; is ambiguous.
        /// </summary>
        internal static string getoptAmbigious {
            get {
                return ResourceManager.GetString("getoptAmbigious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: option &apos;&apos;--{1}&apos;&apos; doesn&apos;t allow an argument.
        /// </summary>
        internal static string getoptArguments1 {
            get {
                return ResourceManager.GetString("getoptArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: option &apos;&apos;{1}{2}&apos;&apos; doesn&apos;t allow an argument.
        /// </summary>
        internal static string getoptArguments2 {
            get {
                return ResourceManager.GetString("getoptArguments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: illegal option -- {1}.
        /// </summary>
        internal static string getoptIllegal {
            get {
                return ResourceManager.GetString("getoptIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: invalid option -- {1}.
        /// </summary>
        internal static string getoptInvalid {
            get {
                return ResourceManager.GetString("getoptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value {0} for parameter &apos;has_arg&apos; .
        /// </summary>
        internal static string getoptInvalidValue {
            get {
                return ResourceManager.GetString("getoptInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: option &apos;&apos;{1}&apos;&apos; requires an argument.
        /// </summary>
        internal static string getoptRequires {
            get {
                return ResourceManager.GetString("getoptRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: option requires an argument -- {1}.
        /// </summary>
        internal static string getoptRequires2 {
            get {
                return ResourceManager.GetString("getoptRequires2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: unrecognized option &apos;&apos;--{1}&apos;&apos;.
        /// </summary>
        internal static string getoptUnrecognized {
            get {
                return ResourceManager.GetString("getoptUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: unrecognized option &apos;&apos;{1}{2}&apos;&apos;.
        /// </summary>
        internal static string getoptUnrecognized2 {
            get {
                return ResourceManager.GetString("getoptUnrecognized2", resourceCulture);
            }
        }
    }
}
